# Generated by Django 5.0.6 on 2026-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='datos_kyc',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalexpediente',
            name='datos_kyc',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
