# Generated by Django 5.0.6 on 2026-06-17 00:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaRestrictiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('OFAC', 'OFAC - Office of Foreign Assets Control'), ('ONU', 'Lista de Sanciones ONU'), ('UE', 'Lista de Sanciones Unión Europea'), ('LOCAL', 'Lista Local')], max_length=10)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('fundamento_legal', models.CharField(blank=True, max_length=500)),
                ('fecha_inclusion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lista Restrictiva',
                'verbose_name_plural': 'Listas Restrictivas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('entidad', models.CharField(blank=True, max_length=255)),
                ('fecha_inicio_cargo', models.DateField(blank=True, null=True)),
                ('fecha_fin_cargo', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PEP',
                'verbose_name_plural': 'PEPs',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalListaRestrictiva',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('OFAC', 'OFAC - Office of Foreign Assets Control'), ('ONU', 'Lista de Sanciones ONU'), ('UE', 'Lista de Sanciones Unión Europea'), ('LOCAL', 'Lista Local')], max_length=10)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('fundamento_legal', models.CharField(blank=True, max_length=500)),
                ('fecha_inclusion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Lista Restrictiva',
                'verbose_name_plural': 'historical Listas Restrictivas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPEP',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('entidad', models.CharField(blank=True, max_length=255)),
                ('fecha_inicio_cargo', models.DateField(blank=True, null=True)),
                ('fecha_fin_cargo', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical PEP',
                'verbose_name_plural': 'historical PEPs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
