# Generated by Django 5.0.6 on 2026-06-17 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('eliminacion', 'Eliminación'), ('consulta', 'Consulta'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
