# Generated by Django 5.0.6 on 2026-06-17 00:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cedula', 'Cédula'), ('rif_nit', 'RIF / NIT'), ('acta_constitutiva', 'Acta Constitutiva'), ('estados_financieros', 'Estados Financieros'), ('referencia_bancaria', 'Referencia Bancaria'), ('certificado_bancario', 'Certificado Bancario'), ('declaracion_renta', 'Declaración de Renta'), ('camara_comercio', 'Cámara de Comercio'), ('contrato', 'Contrato'), ('otro', 'Otro')], max_length=50)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('hash_archivo', models.CharField(blank=True, max_length=64)),
                ('tamano_bytes', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clients.cliente')),
                ('documento_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_posteriores', to='documentos.documento')),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='expedientes.expediente')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cedula', 'Cédula'), ('rif_nit', 'RIF / NIT'), ('acta_constitutiva', 'Acta Constitutiva'), ('estados_financieros', 'Estados Financieros'), ('referencia_bancaria', 'Referencia Bancaria'), ('certificado_bancario', 'Certificado Bancario'), ('declaracion_renta', 'Declaración de Renta'), ('camara_comercio', 'Cámara de Comercio'), ('contrato', 'Contrato'), ('otro', 'Otro')], max_length=50)),
                ('archivo', models.TextField(max_length=100)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('hash_archivo', models.CharField(blank=True, max_length=64)),
                ('tamano_bytes', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.cliente')),
                ('documento_anterior', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documentos.documento')),
                ('expediente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='expedientes.expediente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subido_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Documento',
                'verbose_name_plural': 'historical Documentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
